FROM node:22.11
WORKDIR /frontend

# Copy package files first for caching
COPY frontend/package*.json ./
RUN npm install

# Copy all frontend code
COPY frontend/. ./

EXPOSE 3002
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]





